[tool.poetry]
name = "neuralnet"
version = "0.1.0"
description = "Simple NeuralNet"
authors = ["TitanX <sergey_gusev_007@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
